# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-08 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='event_images')),
                ('location', models.CharField(max_length=600)),
                ('address', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('ver_code', models.CharField(max_length=6)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_images')),
                ('approved', models.BooleanField(default=False)),
                ('fullname', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventually.UserProfile'),
        ),
        migrations.AddField(
            model_name='attendees',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventually.Event'),
        ),
        migrations.AddField(
            model_name='attendees',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventually.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('event_id', 'user_id')]),
        ),
    ]
