# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-08 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event', models.ManyToManyField(to='eventually.Event')),
            ],
        ),
        migrations.RenameField(
            model_name='attendees',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='attendees',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('event', 'user')]),
        ),
    ]
