# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-08 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0004_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fullname',
        ),
    ]
