# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-08 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0005_auto_20190208_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
    ]
