# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0006_auto_20190208_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(),
        ),
    ]
