# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-10 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0006_auto_20190208_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
