# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0008_auto_20190311_1322'),
        ('eventually', '0008_auto_20190312_1508'),
    ]

    operations = [
    ]
