# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0009_auto_20190313_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fb_link',
        ),
        migrations.AddField(
            model_name='event',
            name='fb_page',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
