# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0010_auto_20190313_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='fb_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
