# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 01:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0011_auto_20190314_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Number of Attendees must be a positive number!')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='post_code',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(6, 'UK PostCode is 6-8 Characters')]),
        ),
    ]
