# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventually', '0012_auto_20190314_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
